const TODOS = [
    {
        "id": "whfwfjwiuhfiweuf",
        "title": "Study PHP",
        "note": "",
        "category": "Academic",
        "status": "done", // "not yet started", "in progress", "done"
        // "subtasks": [
        //     "download IDE", 
        //     "submit hw"
        // ],
        // the following data should be stored as objects
        "location": "Taipei",
        "ESD": "3/21",
        "ASD": "3/21",
        "EED": "3/22",
        "AED": "3/21",
        "EST": "15:00",
        "AST": "15:03",
        "EET": "16:00",
        "AET": "17:15",
        "ED": "00:60:00",
        "AD": "01:15:00",
    },
    {
        "id": "gwegreggwegweg",
        "title": "Build Front",
        "note": "w/ Sun Yu",
        "category": "Coding",
        "status": "in progress", // "not yet started", "in progress", "done"
        // "subtasks": [
        //     "download IDE", 
        //     "submit hw"
        // ],
        // the following data should be stored as objects
        "location": "Taipei",
        "ESD": "3/18",
        "ASD": "3/21",
        "EED": "3/25",
        "AED": "",
        "EST": "09:00",
        "AST": "09:16",
        "EET": "12:00",
        "AET": "11:52",
        "ED": "03:00:00",
        "AD": "02:42:00",
    },
    {
        "id": "ijbvinvsd",
        "title": "Buy Milk",
        "note": "全脂鮮乳！！",
        "category": "Home",
        "status": "nys", // "not yet started", "in progress", "done"
        "location": "",
        "ESD": "3/22",
        "ASD": "",
        "EED": "3/22",
        "AED": "",
        "EST": "15:00",
        "AST": "",
        "EET": "15:20",
        "AET": "",
        "ED": "00:20:00",
        "AD": "",
    },
    {
        "id": "kfhwoiueghfeiweuf",
        "title": "Study Python II",
        "note": "ch26-40",
        "category": "Academic",
        "status": "nys", // "not yet started", "in progress", "done"
        "location": "Taoyuan",
        "ESD": "3/23",
        "ASD": "",
        "EED": "",
        "AED": "",
        "EST": "21:00",
        "AST": "",
        "EET": "22:00",
        "AET": "",
        "ED": "00:60:00",
        "AD": "",
    },
    {
        "id": "whfwwkuhgwkbf",
        "title": "Build Front-end",
        "note": "collab w/ Sun Yu",
        "category": "Coding",
        "status": "ip", // "not yet started", "in progress", "done"
        "location": "",
        "ESD": "3/21",
        "ASD": "3/21",
        "EED": "3/22",
        "AED": "3/21",
        "EST": "15:00",
        "AST": "15:03",
        "EET": "16:00",
        "AET": "17:15",
        "ED": "00:60:00",
        "AD": "01:15:00",
    },
    {
        "id": "wh3574398uf",
        "title": "https://youtu.be/dQw4w9WgXcQ",
        "note": "",
        "category": "",
        "status": "nys", // "not yet started", "in progress", "done"
        "location": "",
        "ESD": "3/21",
        "ASD": "",
        "EED": "3/21",
        "AED": "",
        "EST": "",
        "AST": "",
        "EET": "",
        "AET": "",
        "ED": "",
        "AD": "",
    },
    {
        "id": "whfwfiu3hri2u3",
        "title": "Buy Milk",
        "note": "全脂鮮乳！！",
        "category": "Home",
        "status": "nys", // "not yet started", "in progress", "done"
        "location": "",
        "ESD": "3/22",
        "ASD": "",
        "EED": "3/22",
        "AED": "",
        "EST": "15:00",
        "AST": "",
        "EET": "15:20",
        "AET": "",
        "ED": "00:20:00",
        "AD": "",
    },
    {
        "id": "whu3h3f23hoeewweuf",
        "title": "baba yaga",
        "note": "ch26-40",
        "category": "Academic",
        "status": "nys", // "not yet started", "in progress", "done"
        "location": "Taoyuan",
        "ESD": "3/23",
        "ASD": "",
        "EED": "",
        "AED": "",
        "EST": "21:00",
        "AST": "",
        "EET": "22:00",
        "AET": "",
        "ED": "00:60:00",
        "AD": "",
    },
    {
        "id": "w32ih3f8hi8euf",
        "title": "Build Front-end",
        "note": "collab w/ Sun Yu",
        "category": "Coding",
        "status": "ip", // "not yet started", "in progress", "done"
        "location": "",
        "ESD": "3/21",
        "ASD": "3/21",
        "EED": "3/22",
        "AED": "3/21",
        "EST": "15:00",
        "AST": "15:03",
        "EET": "16:00",
        "AET": "17:15",
        "ED": "00:60:00",
        "AD": "01:15:00",
    },
    {
        "id": "whfwlehf899y92iou4",
        "title": "https://youtu.be/dQw4w9WgXcQ",
        "note": "",
        "category": "",
        "status": "nys", // "not yet started", "in progress", "done"
        "location": "",
        "ESD": "3/21",
        "ASD": "",
        "EED": "3/21",
        "AED": "",
        "EST": "",
        "AST": "",
        "EET": "",
        "AET": "",
        "ED": "",
        "AD": "",
    },
    {
        "id": "w29y83020uf",
        "title": "Buy Milk",
        "note": "全脂鮮乳！！",
        "category": "Home",
        "status": "nys", // "not yet started", "in progress", "done"
        "location": "",
        "ESD": "3/22",
        "ASD": "",
        "EED": "3/22",
        "AED": "",
        "EST": "15:00",
        "AST": "",
        "EET": "15:20",
        "AET": "",
        "ED": "00:20:00",
        "AD": "",
    },
    {
        "id": "23t4tgreeuf",
        "title": "Eat Beef Noodles",
        "note": "喜樂滿足牛肉麵QQ",
        "category": "Home",
        "status": "nys", // "not yet started", "in progress", "done"
        "location": "Taoyuan",
        "ESD": "3/23",
        "ASD": "",
        "EED": "",
        "AED": "",
        "EST": "21:00",
        "AST": "",
        "EET": "22:00",
        "AET": "",
        "ED": "00:60:00",
        "AD": "",
    }
]

export default TODOS;